### PR TITLE
markupsafe again

### PR DESCRIPTION
**Pull request by LarryFinn**
i dunno, we get errors about 1.1.0.  so here is 1.1.0.

### CODE REVIEW

**Review by mrwiggles — DISMISSED** [review]
What happens if the Frobnozzle breaks apart again? We've been bitten by this in the past. Can we upgrade to an enterprise-grade Frynozzle? Their demo yesterday was very impressive - I'm convinced they're the right path because they're serverless react using nodejs in spark.

**Comment by mrwiggles** [comment]
Even better, I've heard that Redshift in GCP is great! Can we use that here?

**Comment by LarryFinn** [comment]
unfortunately we are out of adwords credits so we cannot use redshift in gcp @mrwiggles

**Comment by mrwiggles** [comment]
@casey-green Can you reach out to ElasticSearch and see if they can find our adword credits?

**Review by madhurimapoddar — APPROVED** [review]

**Pull request merged**
